In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting numpy>=1.22.4 (from pandas)
  Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 432.3 kB/s eta 0:00:001m389.8 kB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in ./env001/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in ./env001/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 231.2 kB/s eta 0:00:00m eta 0:00:01[36m0:00:02
Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 339.4 kB/s eta 0:00:00m eta 0:00:01[36m0:00:02
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 410.8 kB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 489.6 kB/s eta 0:00:001m482.1 kB/s eta 0:00:01
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-1.26.4 pandas-2.2.2 pytz-2024.1 tzdata-2024.1

In [3]:
import pandas as pd

In [4]:
!pip install faker

Collecting faker
  Downloading Faker-24.11.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in ./env001/lib/python3.10/site-packages (from faker) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./env001/lib/python3.10/site-packages (from python-dateutil>=2.4->faker) (1.16.0)
Downloading Faker-24.11.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 1.5 MB/s eta 0:00:00m eta 0:00:010:01:010m
Installing collected packages: faker
Successfully installed faker-24.11.0

In [5]:
from faker import Faker
fake = Faker()

In [6]:
lista = []

In [7]:
for x in range(0,51):
    lista.append({'nombre': fake.name()})

In [8]:
lista

[{'nombre': 'Tiffany Harrison'},
 {'nombre': 'Dr. Allison Woodard'},
 {'nombre': 'Norma Dougherty'},
 {'nombre': 'Robert Hale'},
 {'nombre': 'Jeffrey Hernandez'},
 {'nombre': 'Sean Brown'},
 {'nombre': 'Thomas Glover'},
 {'nombre': 'Leonard Page'},
 {'nombre': 'Richard Jacobs'},
 {'nombre': 'Rebecca Middleton'},
 {'nombre': 'Kristina Martin'},
 {'nombre': 'Samantha Hancock'},
 {'nombre': 'Devin Manning'},
 {'nombre': 'Rachel Roman'},
 {'nombre': 'Eric Rowe'},
 {'nombre': 'Phillip Miller'},
 {'nombre': 'Christian Peterson'},
 {'nombre': 'Denise Solomon'},
 {'nombre': 'Terry Jones'},
 {'nombre': 'Colleen King'},
 {'nombre': 'James Perkins'},
 {'nombre': 'Anne Mendoza'},
 {'nombre': 'Donald Guzman'},
 {'nombre': 'William Newman'},
 {'nombre': 'Sandra Greene'},
 {'nombre': 'Julie Bradford'},
 {'nombre': 'Benjamin Walsh'},
 {'nombre': 'Oscar Hall'},
 {'nombre': 'Jennifer Rodriguez'},
 {'nombre': 'Daniel Foster'},
 {'nombre': 'Brittany Howell'},
 {'nombre': 'Elizabeth Prince'},
 {'nombre': 'Kyle Calderon'},
 {'nombre': 'Emily Schmidt'},
 {'nombre': 'Nicole Velazquez'},
 {'nombre': 'Gina Rivas'},
 {'nombre': 'Kathryn Li'},
 {'nombre': 'Alicia Moore'},
 {'nombre': 'Anna Walker'},
 {'nombre': 'Jack Ramos'},
 {'nombre': 'Tracy Soto'},
 {'nombre': 'Mallory Hayes'},
 {'nombre': 'Melvin Gonzalez'},
 {'nombre': 'Sarah Underwood'},
 {'nombre': 'Edward Black'},
 {'nombre': 'Mitchell Robbins'},
 {'nombre': 'Tara Page'},
 {'nombre': 'Jennifer Brown'},
 {'nombre': 'Cynthia Coleman'},
 {'nombre': 'Angel Blair'},
 {'nombre': 'Laura Nicholson'}]

In [9]:
data = pd.DataFrame(lista)

In [10]:
data

                 nombre
0      Tiffany Harrison
1   Dr. Allison Woodard
2       Norma Dougherty
3           Robert Hale
4     Jeffrey Hernandez
5            Sean Brown
6         Thomas Glover
7          Leonard Page
8        Richard Jacobs
9     Rebecca Middleton
10      Kristina Martin
11     Samantha Hancock
12        Devin Manning
13         Rachel Roman
14            Eric Rowe
15       Phillip Miller
16   Christian Peterson
17       Denise Solomon
18          Terry Jones
19         Colleen King
20        James Perkins
21         Anne Mendoza
22        Donald Guzman
23       William Newman
24        Sandra Greene
25       Julie Bradford
26       Benjamin Walsh
27           Oscar Hall
28   Jennifer Rodriguez
29        Daniel Foster
30      Brittany Howell
31     Elizabeth Prince
32        Kyle Calderon
33        Emily Schmidt
34     Nicole Velazquez
35           Gina Rivas
36           Kathryn Li
37         Alicia Moore
38          Anna Walker
39           Jack Ramos
40           Tracy Soto
41        Mallory Hayes
42      Melvin Gonzalez
43      Sarah Underwood
44         Edward Black
45     Mitchell Robbins
46            Tara Page
47       Jennifer Brown
48      Cynthia Coleman
49          Angel Blair
50      Laura Nicholson

In [11]:
data.to_csv("misdata.csv", index=False)